### ISSUE TITLE
Request to add Bower package

### ISSUE THREAD

**Issue by eforbus** [renettarenula/anchorific.js#10]
Hi,
First of all, thanks for the great library! I'd like to request that you get it added to bower (http://bower.io/) so that we can use bower to manage anchorific as a dependency.

The process is outlined here: http://bower.io/docs/creating-packages/. Also note that you will need to start using semver (http://semver.org/) versioning in github as bower now requires it. The simple approach would be:

```
git tag v1.0.0
git push origin v1.0.0
```

If you don't want to do this, I will offer to fork your repo and create the bower.json et al.

Thanks again and let me know if you need assistance!

**Comment by mmintel** [comment]
+1
