### ISSUE TITLE
Add option to completely remove anchors from headings

### ISSUE THREAD

**Issue by trslater** [renettarenula/anchorific.js#11]
First of all, great plugin! This works amazingly in conjunction with SinglePageNav (https://github.com/ChrisWojcik/single-page-nav).

It would be really awesome though, to have an option to remove the anchors from the headings completely.

**Comment by renettarenula** [comment]
What do you mean? Remove the anchor text? Or the anchor feature completely?

**Comment by KansoDesign** [comment]
The little number sign beside the heading itself. Like in the example:
    <h1 id="tywin-lannister">Tywin Lannister <a href="#tywin-lannister" class="anchor">#</a></h1>
Just have this instead:
    <h1 id="tywin-lannister">Tywin Lannister</h1>
I think extra link beside the heading is for permalinks? Which makes sense to have, but sometimes you might not need that.

**Comment by renettarenula** [comment]
Hmm, but the anchor link is necessary for the scrollspy to work. And you do want the users to be able to click on the link of your navigation and jump to the correct section right? The anchor link is needed for that. What you can do is perhaps hide the anchor class? Just put <code>display: none;</code> under <code>.anchor</code> if your concern is purely aesthetic.

**Comment by renettarenula** [comment]
Oh, my bad. We do not need it for scrollspy or jumping around sections since it relies on headers.

**Comment by KansoDesign** [comment]
Yes, exactly. It just jumps to the ID, it doesn't have to be an anchor. It's still a good option, so that people can get permalinks for sharing/bookmarking, but it would be nice if it was optional.

Thank you

**Comment by roflcopterDorrie** [comment]
Hi, I have created a pull request with an update for this feature request. 
#23 Simply set `anchorText: false` and it will remove heading anchors.
