### ISSUE TITLE
Option to limit headings used

### ISSUE THREAD

**Issue by trslater** [renettarenula/anchorific.js#12]
Another great feature would be to be able to limit the headings included in the TOC. Something like:

```
minHeading: 2,
maxHeading: 2
```

This way, you could have the TOC built just off of h2's.

**Comment by renettarenula** [comment]
I am planning to add a feature where you can specify the heading that you want to manipulate... something like headings: 'h1, h2'. Is this the same idea?

**Comment by KansoDesign** [comment]
Yeah, that's probably even better than what I was thinking. I'm just thinking, if you have a lot of subheadings, you don't necessarily want a super detailed TOC. The other issue is sometimes you want to use the h1 for the main heading and not have it appear in the TOC, though I guess if it was outside the .content element that would take care of that?

**Comment by peter-mw** [comment]
+1

HI , i need this feature as well :) hope we get this functionality soon

**Comment by spier** [comment]
The current [README](https://github.com/renettarenula/anchorific.js/blob/master/README.md) looks like this feature is already implemented actually, or isn't it?

**Comment by roflcopterDorrie** [comment]
It appears the minified version is not up to date. 
The feature seems to be working using https://github.com/renettarenula/anchorific.js/blob/master/src/anchorific.js 
but not using 
https://github.com/renettarenula/anchorific.js/blob/master/min/anchorific.min.js

**Comment by spier** [comment]
@roflcopterDorrie great catch! Do you want to send a PR that fixes that, or shall I?

**Comment by chaloum** [comment]
Has this feature been added to the https://cdnjs.cloudflare.com/ajax/libs/anchorific/0.1.2/min/anchorific.min.js version and are the configuration options minHeading: 2, maxHeading: 2, ?

thanks
