### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by c0c0t3** [renettarenula/anchorific.js#15]
Hi,

I try to implant your plugin in your website, but I can't and I don't know why. I tried several ways to call your plugin, witho or without noconflict, with jQuery, with $...

But I can't load it...

Uncaught TypeError: jQuery(...).anchorific is not a function

can I have your email for a little support if it's possible ? thank you !  :)

**Comment by renettarenula** [comment]
Hmm, not sure why. What version of jQuery are you using?

**Comment by c0c0t3** [comment]
I rewtrited my plugin in inspuiration of your plugin, but thank you. I was using jQuery v1.11.3
Finally, I scrapp all h3 from my page, create a section, put a bootstrap nav with scrollspy... :)

thank you for your time

**Comment by Prekshapatel** [comment]
I also have the same issue after updating the Jquery version with Drupal core. JQuery version is 3.4.1 and started getting error  Uncaught TypeError: $(...).anchorific is not a function
