### ISSUE TITLE
add tags for every version

### ISSUE THREAD

**Issue by maruilian11** [renettarenula/anchorific.js#20]
hi, recently we want to add your lib on https://cdnjs.com, could you please consider adding git tags for every released version so that we can use **git auto-update config** to add them to cdnjs.
thank you very much!

btw, does `css/style.css` also need to be hosted? thank you :smile: 

https://github.com/cdnjs/cdnjs/issues/6925

**Comment by renettarenula** [comment]
Sure, I can do that. I don't think so css needs to be hosted though. Users can always add in their own CSS.

**Comment by maruilian11** [comment]
thank you! i will change version in PR after you add the version number :smiley:

**Comment by maruilian11** [comment]
@renettarenula any update? thanks~

**Comment by renettarenula** [comment]
@maruilian11 my bad. Been quite busy that I forgot about this. I will tag a version tomorrow!!

**Comment by renettarenula** [comment]
Hey, I tagged the project as v1.0. I am closing this issue but feel free to let me know if you need anything else. :)
