### ISSUE TITLE
Not an issue but improvements that I have made

### ISSUE THREAD

**Issue by tonyhallett** [renettarenula/anchorific.js#21]
Hi Ren,

I have expanded upon your code and thought that you might want to consider using mine as a version 2.  
I have a blog entry on it http://ctrlcsharpetc.blogspot.co.uk/2016/10/anchorific-improved.html and I have uploaded the changed javascript to https://github.com/tonyhallett/anchorificImproved.

Perhaps you could tell me your thoughts when you have the time.

Thanks

Tony

**Comment by renettarenula** [comment]
Please create a pull request if you want it merge.
