### ISSUE TITLE
Link to demo page is broken

### ISSUE THREAD

**Issue by spier** [renettarenula/anchorific.js#22]
Hi,

anchorific is a great idea, I was looking for something just like this.

I found that the demo page is broken:
http://renaysha.me/anchorific-js

Could be good for new users to fix, so that they can try it out more quickly.

**Comment by alanshum** [comment]
wayback machine is a good friend:
https://web.archive.org/web/20150315041828/http://renaysha.me/anchorific-js/

**Comment by spier** [comment]
Hi @alanshum. Thanks for the answer.

Please come again though, what did you want to say with the wayback machine link?
